### ISSUE TITLE
javascript bug when editing content

### ISSUE THREAD

**Issue by ahmadalukah** [Alex-D/Trumbowyg#437]
Hi, I opened the editor in my website and wrote:
```
<script>
console.log('hello')
</script>
```
inside the editor text area (without pre plugin), it showed as a text , this is great. But when I retrieved the content to edit it I got this error
```
Uncaught SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at Function.globalEval (https://example.com/js/jquery.js:328:5)
    at jQuery.fn.init.domManip (https://example.com/js/jquery.js:5435:16)
    at jQuery.fn.init.append (https://example.com/js/jquery.js:5218:15)
    at jQuery.fn.init.<anonymous> (https://example.com/js/jquery.js:5333:18)
    at jQuery.access (https://example.com/js/jquery.js:3491:8)
    at jQuery.fn.init.html (https://example.com/js/jquery.js:5300:10)
    at o.buildEditor (https://example.com/js/trumbowyg.min.js:2:6126)
    at o.init (https://example.com/js/trumbowyg.min.js:2:5386)
    at o (https://example.com/js/trumbowyg.min.js:2:5180)
```
and the debugger VM132 showed this:
```
</p><p>console.log('hello')</p><p>
```

without the edit form.

I don't know if this is considered a bug or not, Do I have to escape and delete anything from the text when retrieving it to the view? Thanks

**Comment by Alex-D** [comment]
> when I retrieved the content to edit it

I didn't understand what you meen :/

**Comment by fkomaralp** [comment]
He is (me too) cannot edit content. How can I reload my html content?. If I use 
` $('#content').trumbowyg('html', "{!! $page->content !!}" );` its return an error, like double/single quotes confilict error.

**Comment by fkomaralp** [comment]
Ok found a solution like,
`$('#content').trumbowyg('html', "{!! str_replace("\"","\\\"",$page->content) !!}" );`
